# spring.application.name=ServiceRegistry

spring:
  application:
    name: ServiceRegistry
server:
  port: 8761 # Puerto por defecto de Eureka
eureka:
  client:
    registerWithEureka: false # No se registra a si mismo
    fetchRegistry: false # No necesita consultar el registro
