# spring.application.name=Gateway

spring:
  application:
    name: Gateway
  profiles:
    active: default

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clans_service
          # uri: http://localhost:9000/
          uri: lb://clans
          predicates:
            - Path=/clans/**

server:
  port: 8080

#Eureka configuration
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
