services:
  db:
    image: mysql:8
    container_name: microservices_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: riwi_db_meta
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  # Para copiar información existente en un script
  # db_data: ./db_data.sql
  db_data:
